// src/services/alertNotifier.ts
// ─────────────────────────────────────────────────────────────────────────────
// EI-Core Alert Notifier — Slack & Microsoft Teams
//
// All public functions are fire-and-forget safe.
// Circular-import safe: does NOT import from eicore.ts.
// ─────────────────────────────────────────────────────────────────────────────

import { pool } from '../db';
import { decryptToken } from '../utils/crypto';
import { OrgSignals } from './signalEngine';

// Minimal shape we need from OrgInsightResponse — avoids circular import
export interface AlertInsightData {
  executive_summary: string;
  org_health_score: number;
  top_at_risk: {
    employee_name: string;
    primary_signal: string;
    signal_value: number;
    recommended_action: string;
  }[];
  recommended_actions: {
    priority: string;
    action: string;
    target: string;
    rationale: string;
  }[];
}

// ─────────────────────────────────────────────────────────────────────────────
// SLACK
// ─────────────────────────────────────────────────────────────────────────────

export async function sendSlackMessage(webhookUrl: string, payload: object): Promise<void> {
  const res = await fetch(webhookUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });
  if (!res.ok) {
    throw new Error(`Slack webhook HTTP ${res.status}: ${await res.text()}`);
  }
}

function buildSlackPayload(insight: AlertInsightData, signals: OrgSignals): object {
  const urgency      = signals.critical_count > 0 ? '🚨 Critical Alert' : '⚠️ High Priority Alert';
  const healthEmoji  = insight.org_health_score >= 75 ? '🟢' : insight.org_health_score >= 50 ? '🟡' : '🔴';
  const immediateAct = insight.recommended_actions.find(a => a.priority === 'immediate')?.action
    ?? 'Review flagged employees in VeloxSync.';

  const atRiskLines = insight.top_at_risk.slice(0, 3)
    .map(e => `• *${e.employee_name}* — ${e.primary_signal.replace(/_/g, ' ')} at ${e.signal_value}/100`)
    .join('\n');

  return {
    text: `${urgency}: EI-Core Workforce Alert`,
    blocks: [
      {
        type: 'header',
        text: { type: 'plain_text', text: `${urgency} — EI-Core Workforce Alert` },
      },
      {
        type: 'section',
        text: { type: 'mrkdwn', text: insight.executive_summary },
      },
      {
        type: 'section',
        fields: [
          { type: 'mrkdwn', text: `*${healthEmoji} Org Health*\n${insight.org_health_score}/100` },
          { type: 'mrkdwn', text: `*👥 At-Risk*\n${signals.at_risk_count} employees` },
          { type: 'mrkdwn', text: `*🔥 Avg Burnout*\n${signals.avg_burnout_probability}/100` },
          { type: 'mrkdwn', text: `*🚨 Critical*\n${signals.critical_count} employees` },
        ],
      },
      ...(insight.top_at_risk.length > 0
        ? [{
            type: 'section',
            text: { type: 'mrkdwn', text: `*Top At-Risk Employees:*\n${atRiskLines}` },
          }]
        : []),
      {
        type: 'section',
        text: { type: 'mrkdwn', text: `*Immediate Action:* ${immediateAct}` },
      },
      { type: 'divider' },
      {
        type: 'context',
        elements: [
          { type: 'mrkdwn', text: `Generated by *VeloxSync EI-Core* · ${new Date().toUTCString()}` },
        ],
      },
    ],
  };
}

export async function sendSlackOrgAlert(
  orgId: number,
  insight: AlertInsightData,
  signals: OrgSignals,
): Promise<void> {
  const row = await pool.query(
    'SELECT webhook_url FROM slack_integrations WHERE organization_id = $1',
    [orgId],
  );
  if (row.rows.length === 0) return; // no Slack connected for this org

  const webhookUrl = decryptToken(row.rows[0].webhook_url);
  await sendSlackMessage(webhookUrl, buildSlackPayload(insight, signals));
  console.log(`[AlertNotifier] Slack alert sent for org ${orgId}`);
}

// ─────────────────────────────────────────────────────────────────────────────
// MICROSOFT TEAMS
// ─────────────────────────────────────────────────────────────────────────────

export async function sendTeamsMessage(webhookUrl: string, payload: object): Promise<void> {
  const res = await fetch(webhookUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });
  if (!res.ok) {
    throw new Error(`Teams webhook HTTP ${res.status}: ${await res.text()}`);
  }
}

function buildTeamsPayload(insight: AlertInsightData, signals: OrgSignals): object {
  const urgency     = signals.critical_count > 0 ? '🚨 Critical Alert' : '⚠️ High Priority Alert';
  const healthColor = insight.org_health_score >= 75 ? 'Good' : insight.org_health_score >= 50 ? 'Warning' : 'Attention';
  const immediateAct = insight.recommended_actions.find(a => a.priority === 'immediate')?.action
    ?? 'Review flagged employees in VeloxSync.';

  const atRiskBlocks = insight.top_at_risk.slice(0, 3).map(e => ({
    type: 'TextBlock',
    text: `• **${e.employee_name}** — ${e.primary_signal.replace(/_/g, ' ')} (${e.signal_value}/100)`,
    wrap: true,
    size: 'Small',
  }));

  return {
    type: 'message',
    attachments: [{
      contentType: 'application/vnd.microsoft.card.adaptive',
      content: {
        $schema: 'http://adaptivecards.io/schemas/adaptive-card.json',
        type: 'AdaptiveCard',
        version: '1.3',
        body: [
          {
            type: 'TextBlock',
            text: `EI-Core Workforce Alert — ${urgency}`,
            weight: 'Bolder',
            size: 'Large',
            color: healthColor,
            wrap: true,
          },
          {
            type: 'TextBlock',
            text: insight.executive_summary,
            wrap: true,
          },
          {
            type: 'FactSet',
            facts: [
              { title: 'Org Health Score',      value: `${insight.org_health_score}/100` },
              { title: 'At-Risk Employees',      value: String(signals.at_risk_count) },
              { title: 'Critical Employees',     value: String(signals.critical_count) },
              { title: 'Avg Burnout',            value: `${signals.avg_burnout_probability}/100` },
            ],
          },
          ...(insight.top_at_risk.length > 0 ? [
            {
              type: 'TextBlock',
              text: 'Top At-Risk Employees',
              weight: 'Bolder',
              size: 'Medium',
              spacing: 'Medium',
            },
            ...atRiskBlocks,
          ] : []),
          {
            type: 'TextBlock',
            text: `**Immediate Action:** ${immediateAct}`,
            wrap: true,
            spacing: 'Medium',
          },
          {
            type: 'TextBlock',
            text: `Generated by VeloxSync EI-Core · ${new Date().toUTCString()}`,
            size: 'Small',
            color: 'Light',
            spacing: 'Medium',
          },
        ],
        actions: [{
          type: 'Action.OpenUrl',
          title: 'Open VeloxSync Dashboard',
          url: process.env.FRONTEND_URL ?? 'https://app.veloxsync.com',
        }],
      },
    }],
  };
}

export async function sendTeamsOrgAlert(
  orgId: number,
  insight: AlertInsightData,
  signals: OrgSignals,
): Promise<void> {
  const row = await pool.query(
    'SELECT webhook_url FROM teams_integrations WHERE organization_id = $1',
    [orgId],
  );
  if (row.rows.length === 0) return; // no Teams connected for this org

  const webhookUrl = decryptToken(row.rows[0].webhook_url);
  await sendTeamsMessage(webhookUrl, buildTeamsPayload(insight, signals));
  console.log(`[AlertNotifier] Teams alert sent for org ${orgId}`);
}
